//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTestDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_tool
    {
        public int id { get; set; }
        public string tool_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> status_time { get; set; }
        public string area { get; set; }
        public Nullable<int> move { get; set; }
    }
}
